amplitude.getInstance().setUserProperties({'website_language':languageCode});window.selected_property_flag=0;jQuery(function($){var personalization=getCookie('personalization');if(personalization==null){if(custom_client_ID!=''){var personalizationData={clientID:custom_client_ID}
setCookie('personalization',JSON.stringify(personalizationData),365)}}
var client_id=getCookie('custom_client_id');if(client_id==null){if(custom_client_ID!=''){setCookie('custom_client_id',custom_client_ID,365)}}
$('.filter-special-character input').on('input',function(){var c=this.selectionStart,r=/[^a-z0-9 ]/gi,v=$(this).val();if(r.test(v)){$(this).val(v.replace(r,''));c--}
this.setSelectionRange(c,c)});$('.allow-only-numbers input').on('input',function(){var c=this.selectionStart,r=/[^0-9]/gi,v=$(this).val();if(r.test(v)){$(this).val(v.replace(r,''));c--}
this.setSelectionRange(c,c)});$('.allow-only-alphabets input').on('input',function(){var c=this.selectionStart,r=/[^a-z ]/gi,v=$(this).val();if(r.test(v)){$(this).val(v.replace(r,''));c--}
this.setSelectionRange(c,c)});$('.filter-special-character .has_city input').on('input',function(e){v=$(this).val();if(v.length>=50){console.log('Max length is greater than 50');$(this).val($(this).val().substr(0,50))}});$('.filter-symbols input').on('input',function(){var c=this.selectionStart,r=/[~`!@#$%\^&*()+=_\-\[\]\\';,./{}|\\":<>\?0-9]/gi,v=$(this).val();if(r.test(v)){$(this).val(v.replace(r,''));c--}
this.setSelectionRange(c,c)});$('.filter-special-character input').on('input',function(){var c=this.selectionStart,r=/[^a-z0-9 ]/gi,v=$(this).val();if(r.test(v)){$(this).val(v.replace(r,''));c--}
this.setSelectionRange(c,c)});$('.allow-only-numbers input').on('input',function(){maxlength=15;var c=this.selectionStart,r=/[^0-9 ]/gi,v=$(this).val();if(v.length>15){$(this).val($(this).val().substr(0,maxlength))}
if(r.test(v)){$(this).val(v.replace(r,''));c--}
this.setSelectionRange(c,c)});$('.filter-symbols input').on('input',function(){var c=this.selectionStart,r=/[~`!@#$%\^&*()+=_\-\[\]\\';,./{}|\\":<>\?0-9]/gi,v=$(this).val();if(r.test(v)){$(this).val(v.replace(r,''));c--}
this.setSelectionRange(c,c)});$('.modal').on('hidden.bs.modal',function(){var id=$(this).find('div.modal-body div.gform_anchor').attr('id');$(this).find('div.modal-body').html(formHtml[id]);gfromFilterSpecialCharacters()});$('.modal').on('shown.bs.modal',function(){gfromFilterSpecialCharacters()});var checkMobile=window.matchMedia("(max-width: 767px)");var checkMobileTablet=window.matchMedia("(max-width: 991px)");var w=$(document).width();var h=$(document).height();$(".communities-menu").css('width',w);$(".communities-menu").css('height',h);$('.communities-tab').click(function(){$('.communities-menu').width($(window).width());$('.communities-menu').height($(window).height());$("body").toggleClass("body-fixed-position");$('.communities-menu').slideToggle();$('.communities-tab').toggleClass('active');event.stopPropagation();return!1});$(document).click(function(e){if($(e.target).is(".communities-featured-container")===!1){$("body").removeClass("body-fixed-position");$('.communities-tab').removeClass('active')}});$('.share-btn').click(function(){$('.sharing-options').slideToggle();$('.share-btn').toggleClass('active');event.stopPropagation();return!1});$('.cookie-disclaimer .btn-accept').on('click',function(){$('.cookie-disclaimer').hide()});function _deprecated_getCommByType(types=null){if(types==null)
return;var jqXHR=jQuery.ajax({type:"POST",url:ct_ajax_script.ajaxurl,data:{action:'get_community_by_type',types:types},success:function(data){cbCommByType(data)},error:function(jqXHR,textStatus,errorThrown){}});return jqXHR.responseText}
function _deprecated_cbCommByType(data){var data1=jQuery.parseJSON(data);$(data1).each(function(i,val){$.each(val,function(key,val){})});return data}
window.CommunityDDBeforeAJax;CommunityDDBeforeAJax=!1;$('#mobile-property-apply').click(function(){$('#propertyTypeModal').hide();$('#btn-show-filters').hide();$('.homepage-mobile-filter-section #prop_search_mobile_form').show();$('#community-for-mobile .search-val').removeClass('selected-val').text(all_communities_text);var checkedBoxes=$('input[name="p-type[]"]:checked').length;var sel_property=[];$('input[name="p-type[]"]:checked').each(function(){sel_property.push(this.value)});if(sel_property.length!=0){var CommByTpe=getCommByType(sel_property);if(checkedBoxes==1){selected_msg_label=checkedBoxes+' '+property_type_text}
if(checkedBoxes>1){selected_msg_label=checkedBoxes+' '+properties_type_text}
$('#property-for-mobile .search-val').addClass('selected-val').text(selected_msg_label)}else{$('.community-options-mobile').html(CommunityDDBeforeAJax);$('#property-for-mobile .search-val').removeClass('selected-val').text(any_text);return}
if(!CommunityDDBeforeAJax){CommunityDDBeforeAJax=$('.community-options-mobile').html()}});$('.home-search-component input[name="p-type[]"]').on('change',function(){checkAllSearchFilters();var checkedBoxes=$('input[name="p-type[]"]:checked').length;var selected_msg_label="";var sel_property=[];$('.community-selection').find('span.search-val').removeClass('selected-val').text(all_communities_text);$('input[name="p-type[]"]:checked').each(function(){sel_property.push(this.value)});if(sel_property.length!=0){var CommByTpe=getCommByType(sel_property);$('.primary-communitylist-container').addClass('property-community-list');if(checkedBoxes==1){selected_msg_label=checkedBoxes+' '+property_type_text}
if(checkedBoxes>1){selected_msg_label=checkedBoxes+' '+properties_type_text}
if($('#gform_16').length>0){$('#gform_16 #input_16_44').val(sel_property.join(','))}
$('.property-type-selection').find('span.search-val').addClass('selected-val').text(selected_msg_label);$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}else{$('.community-options-desktop').html(CommunityDDBeforeAJax);$('.property-type-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('.primary-communitylist-container').removeClass('property-community-list');return}
if(!CommunityDDBeforeAJax){CommunityDDBeforeAJax=$('.community-options-desktop').html()}});$('input[name="p-type[]"]').on('change',function(){var selected_msg_label="";var checkedBoxes=$(this).closest('.property-type-options').find('input[name="p-type[]"]:checked').length;if(checkedBoxes>0){if(checkedBoxes==1){selected_msg_label=checkedBoxes+' '+property_type_text}
if(checkedBoxes>1){selected_msg_label=checkedBoxes+' '+properties_type_text}
$('.property-type-selection').find('span.search-val').addClass('selected-val').text(selected_msg_label);$('#property-for-mobile .search-val').addClass('selected-val').text(selected_msg_label);$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset');$('#map_search_form #propertyTyp .filter-panel-details .filter-btns .filter-btn[type=reset]').addClass('active-clear').css('pointer-events','unset')}else{$('.property-type-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('#property-for-mobile .search-val').removeClass('selected-val').text(any_text);$('#map_search_form #propertyTyp .filter-panel-details .filter-btns .filter-btn[type=reset]').removeClass('active-clear').css('pointer-events','none')}
if(checkedBoxes==0||checkedBoxes>3){selected_property_flag=0}else{if(checkedBoxes>=1&&checkedBoxes<=3){$(this).closest('.property-type-options').find('input[name="p-type[]"]:checked').each(function(){if(this.value!="Villa"&&this.value!="Townhouse"&&this.value!="Plot"){selected_property_flag=0;return!1}else{if(this.value=="Villa"||this.value=="Townhouse"||this.value=="Plot"){selected_property_flag=1}}})}}
if(selected_property_flag){if(checkMobile.matches){$('#floor-for-mobile').addClass("d-none")}else{$('.floor-selection').addClass("d-none")}}else{if(checkMobile.matches){$('#floor-for-mobile').removeClass("d-none")}else{$('.floor-selection').removeClass("d-none")}}});function checkAllSearchFilters(){if($('input[name="comm[]"]:checked').length==0&&$('input[name="bed[]"]:checked').length==0&&$('input[name="p-type[]"]:checked').length==0&&$('select[name="max-price"]').val()==100000000&&$('select[name="min-price"]').val()==0&&$('select[name="floor"]').val()=='All'&&$('select[name="max-area"]').val()==50000&&$('select[name="min-area"]').val()==0){$('#clear-all-fields').removeClass('active-clearall');$('.clear-selection.all').removeClass('active-clearall').css('pointer-events','unset')}
if($('input[name="comm[]"]:checked').length==0&&$('input[name="p-type[]"]:checked').length==0&&$('select[name="floor"]').val()=='All'&&$('select[name="max-area"]').val()==50000&&$('select[name="min-area"]').val()==0){$('#clear-all-fields').removeClass('active-clearall');$('.clear-selection.all').removeClass('active-clearall').css('pointer-events','unset')}}
$('#propertyTypeModal').on('hidden.bs.modal',function(){$('#btn-show-filters').hide();$('.homepage-mobile-filter-section #prop_search_mobile_form').show()});$('#communityModal').on('hidden.bs.modal',function(){$('#btn-show-filters').hide();$('.homepage-mobile-filter-section #prop_search_mobile_form').show()});$('#priceModal').on('hidden.bs.modal',function(){$('#btn-show-filters').hide();$('.homepage-mobile-filter-section #prop_search_mobile_form').show()});$('#bedroomsModal').on('hidden.bs.modal',function(){$('#btn-show-filters').hide();$('.homepage-mobile-filter-section #prop_search_mobile_form').show()});$.fn.showOption=function(){this.each(function(){if(this.tagName=="OPTION"){var opt=this;if($(this).parent().get(0).tagName=="SPAN"){var span=$(this).parent().get(0);$(span).replaceWith(opt);$(span).remove()}
opt.disabled=!1;$(opt).show()}});return this}
$.fn.hideOption=function(){this.each(function(){if(this.tagName=="OPTION"){var opt=this;if($(this).parent().get(0).tagName=="SPAN"){var span=$(this).parent().get(0);$(span).hide()}else{$(opt).wrap("span").hide()}
opt.disabled=!0}});return this}
$(document.body).on("click",function(event){var el=event.srcElement;if(!$(el).hasClass("trigger")&&(!$(el).is("a")))
$(".communities-menu").slideUp()});$(document.body).on("click",function(event){var el=event.srcElement;if(!$(el).hasClass("trigger")&&(!$(el).is("a")))
$(".sharing-options").slideUp()});$(document).mouseup(function(e){var search_form=$(".prop-search-bar");var mobile_search_form=$(".homepage-mobile-filter-section");if(!search_form.is(e.target)&&search_form.has(e.target).length===0){if(!checkMobile.matches){if($(".price-range-selection .select-sec-options").is(":visible")){$('.price-range-selection label.search-fld').removeClass("active")}
if($(".property-type-selection .select-sec-options").is(":visible")){$('.property-type-selection label.search-fld').removeClass("active")}
if($(".bedroom-selection .select-sec-options").is(":visible")){$('.bedroom-selection label.search-fld').removeClass("active")}
if($(".floor-selection .select-sec-options").is(":visible")){$('.floor-selection label.search-fld').removeClass("active")}
if($(".area-selection .select-sec-options").is(":visible")){$('.area-selection label.search-fld').removeClass("active")}
if($(".property-selection .select-sec-options").is(":visible")){$('.property-selection label.search-fld').removeClass("active")}
if($('.community-options').is(":visible")){$('.community-selection label.search-fld').toggleClass('active')}}}
if(!mobile_search_form.is(e.target)&&mobile_search_form.has(e.target).length===0){$(".homepage-mobile-filter-section #prop_search_mobile_form").hide();$(".home-hero-section .prop-search-bar").removeClass('position-property-search');$(".hero-background-overlay").removeClass('set-hero-overlay');$("#btn-show-filters").show()}});$(document).ready(function(){if($('.emr-custom-select').length){$('.emr-custom-select').selectpicker()}
if($('.phone-tab').length<=0&&$('.watsapp-tab').length<=0&&$('.register-tab').length<=0){$("ul li.lang-tab").addClass("mr-5")}else{$("ul li.lang-tab").removeClass("mr-5")}
if($('.home-search-component').length>0){$('.home-search-component input[name="comm[]"]:checkbox').prop('checked',!1);$('.community-selection').find('span.search-val').removeClass('selected-val').text(all_communities_text);$('.home-search-component input[name="bed[]"]:checkbox').prop('checked',!1);$('.bedroom-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('.home-search-component select[name="min-price"] option[value="0"]').prop("selected",!0);$('.home-search-component select[name="max-price"] option[value="100000000"]').prop("selected",!0);$('.home-search-component .price-range-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('.home-search-component input[name="p-type[]"]:checkbox').prop('checked',!1);$('.property-selection').find('span.search-val').removeClass('selected-val').text(any_text)}
if(!checkMobileTablet.matches){$(window).scroll(function(){if($(window).scrollTop()>100){$('.cookie-disclaimer').addClass('stick-top')}else if($(window).scrollTop()<=100){$('.cookie-disclaimer').removeClass('stick-top')}
if($('#myElementToStick').length&&$('#myElementToStick').offset().top+$("#myElementToStick").height()>$("#colophon").offset().top){$('#myElementToStick').css('top',-($("#myElementToStick").offset().top+$("#myElementToStick").height()-$("#colophon").offset().top))}})}
if(device!="desktop"||device_tablet||window.innerWidth<991){$($('.community-menu-item').html()).insertAfter('#menu-mobile-menu > li:nth-child(2)');setTimeout(function(){const menu=new Mmenu(document.querySelector('#mobile_nav'),{navbars:[{content:['close']},{content:['prev']},]});$("#mobile_nav").find(".mm-navbar__btn.mm-btn_prev").append("Back to Menu");const api=menu.API;api.bind("close:after",function(){api.closeAllPanels()});$('.get-touch-btn').click(function(ev){ev.preventDefault();if($("#mobile_nav").hasClass("mm-menu_opened")){api.close()}});$('.instant-video-call').on('click',function(){var checkExist=setInterval(function(){if($('.calendly-overlay').length){if($("#mobile_nav").hasClass("mm-menu_opened")){api.close()}
clearInterval(checkExist)}},50)})
$('.ir-enq-btn').on('click',function(ev){if($("#mobile_nav").hasClass("mm-menu_opened")){api.close()}})},800)}
$(window).scroll(function(){var distanceFromTop=$(document).scrollTop();if(distanceFromTop>=200){$('.prop-search-mobile-form').addClass('search-sticky');if($('.prop-search-mobile-form').hasClass('search-sticky')&&$('#collapseFilter').hasClass('show')){$('body').css('overflow-y','hidden')}}else{$('.prop-search-mobile-form').removeClass('search-sticky')}});$("#collapseFilter").on('show.bs.collapse',function(){if($('.prop-search-mobile-form').hasClass('search-sticky')){$('body').css('overflow-y','hidden')}});$("#collapseFilter").on('hide.bs.collapse',function(){$('body').css('overflow-y','scroll')});$(".communities-menu-featured .communities-featured-block").removeClass("come-in");var currentItem;var itemsFound;var min_price_selection;var max_price_selection;if(checkMobile.matches){$('#floor-for-mobile').removeClass("d-none")}else{$('.floor-selection').removeClass("d-none")}
if($('select[name="max-price"]').val()==0){$('select[name="max-price"] option[value="100000000"]').prop("selected",!0)}
if($('select[name="max-area"]').val()==0||$('select[name="max-area"]').val()==50000){$('select[name="max-area"] option[value="50000"]').prop("selected",!0)}
if($('input[name="comm[]"]:checked').length>0){$('.community-selection').find('span.search-val').addClass('selected-val');$('.community-options .filter-bottom .clear-selection, .community-selection .filter-bottom .clear-selection').addClass('active-clear');$('#community-for-mobile').find('span.search-val').addClass('selected-val');$('#mobile-clear-community').addClass('active-clear');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}
if($('input[name="bed[]"]:checked').length>0){$('.bedroom-selection').find('span.search-val').addClass('selected-val');$('#clear-bedrooms').addClass('active-clear');$('#bedroom-for-mobile').find('span.search-val').addClass('selected-val');$('#mobile-clear-bedrooms').addClass('active-clear');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}
if($('select[name="max-price"]').val()>0){if($('select[name="max-price"]').val()==100000000&&$('select[name="min-price"]').val()==0){$('.price-range-selection, #price-for-mobile').find('span.search-val').removeClass('selected-val')}else if($('select[name="max-price"]').val()==20000000&&$('select[name="min-price"]').val()==0){$('.price-range-selection').find('span.search-val').removeClass('selected-val')}else{if($('select[name="min-price"]').val()>0||$('select[name="max-price"]').val()>0){$('.price-range-selection').find('span.search-val').addClass('selected-val');$('.price-range-selection .filter-bottom .clear-selection').addClass('active-clear');$('#mobile-clear-price').addClass('active-clear');$('#price-for-mobile').find('span.search-val').addClass('selected-val');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}}}
if($('select[name="floor"]').val()>=1){$('.floor-selection').find('span.search-val').addClass('selected-val');$('#clear-floor-mobile').addClass('active-clear');$('.floor-selection .filter-bottom .clear-selection').addClass('active-clear');$('#floor-for-mobile').find('span.search-val').addClass('selected-val');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}
if($('select[name="min-area"]').val()>100){$('.area-selection .filter-bottom .clear-selection').addClass('active-clear');$('#clear-area-mobile').addClass('active-clear');$('#area-for-mobile').find('span.search-val').addClass('selected-val');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}
if($('input[name="p-type[]"]:checked').length>0){var selectedPropTypes=[];$('.property-type-selection').find('span.search-val').addClass('selected-val');$('#clear-property').addClass('active-clear');$('#property-for-mobile').find('span.search-val').addClass('selected-val');$('#mobile-clear-property').addClass('active-clear');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset');var sel_property=[];$('input[name="p-type[]"]:checked').each(function(){sel_property.push(this.value)});if(sel_property.length<=3){$('input[name="p-type[]"]:checked').each(function(){if(this.value!="Villa"&&this.value!="Townhouse"&&this.value!="Plot"){selected_property_flag=0;return!1}else{if(this.value=="Villa"||this.value=="Townhouse"||this.value=="Plot"){selected_property_flag=1}}})}
if(selected_property_flag){if(checkMobile.matches){$('#floor-for-mobile').addClass("d-none")}else{$('.floor-selection').addClass("d-none")}}else{if(checkMobile.matches){$('#floor-for-mobile').removeClass("d-none")}else{$('.floor-selection').removeClass("d-none")}}}
if($('input[name="prop[]"]:checked').length>0){$('.property-selection').find('span.search-val').addClass('selected-val');$('.property-selection .filter-bottom .clear-selection').addClass('active-clear');$('#property-comm-for-mobile').find('span.search-val').addClass('selected-val');$('#mobile-clear-property').addClass('active-clear');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}
if($('select[name="min-floor"]').val()>1||$('select[name="max-floor"]').val()>1){if($('select[name="min-floor"]').val()==1){$('.floor-selection').find('span.search-val').removeClass('selected-val');$('#floor-for-mobile span.search-val').removeClass('selected-val');$('.floor-selection .filter-bottom .clear-selection').removeClass('active-clear');$('.floor-selection').find('span.search-val').text(all_text)}else{$('.floor-selection').find('span.search-val').addClass('selected-val');$('#floor-for-mobile span.search-val').addClass('selected-val')}}
if($('select[name="min-area"]').val()>0||$('select[name="max-area"]').val()<50000){if($('select[name="min-area"]').val()==0&&$('select[name="max-area"]').val()==50000){$('.area-selection').find('span.search-val').removeClass('selected-val');$('#area-for-mobile span.search-val').removeClass('selected-val');$('.area-selection').find('span.search-val').text(any_text);$('#area-for-mobile span.search-val').text(any_text);$('.area-selection .filter-bottom .clear-selection').removeClass('active-clear')}else{$('.area-selection').find('span.search-val').addClass('selected-val');$('#area-for-mobile span.search-val').addClass('selected-val');$('.area-selection .filter-bottom .clear-selection').addClass('active-clear')}}
$('input[name="comm[]"]').on('change',function(){checkAllSearchFilters();if(checkMobileTablet.matches){if($('input[name="comm[]"]:checked').length<1){$('#mobile-clear-community').removeClass('active-clear').css('pointer-events','none')}else{$('#mobile-clear-community').addClass('active-clear').css('pointer-events','unset');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}}else{if($('#prop_search_form input[name="comm[]"]:checked').length<1){$('#clear-community, #clear-map-community').removeClass('active-clear').css('pointer-events','none')}else{$('#clear-community, #clear-map-community').addClass('active-clear').css('pointer-events','unset')}}});$('input[name="bed[]"]').on('change',function(){checkAllSearchFilters();if(checkMobileTablet.matches){if($('input[name="bed[]"]:checked').length<1){$('#mobile-clear-bedrooms').removeClass('active-clear').css('pointer-events','none')}else{$('#mobile-clear-bedrooms').addClass('active-clear');$('.clear-selection.all').addClass('active-clearall');$('#mobile-clear-bedrooms, .clear-selection.all').css('pointer-events','unset')}}else{if($('#prop_search_form input[name="bed[]"]:checked').length<1){$('#clear-bedrooms').removeClass('active-clear').css('pointer-events','none');$('#map_search_form #propertyBeds .filter-panel-details .filter-btns .filter-btn[type=reset]').removeClass('active-clear').css('pointer-events','none')}else{$('#clear-bedrooms').addClass('active-clear').css('pointer-events','unset');$('#map_search_form #propertyBeds .filter-panel-details .filter-btns .filter-btn[type=reset]').addClass('active-clear').css('pointer-events','unset')}}});$('input[name="p-type[]"]').on('change',function(){checkAllSearchFilters();if(checkMobileTablet.matches){if($('input[name="p-type[]"]:checked').length<1){$('#mobile-clear-property').removeClass('active-clear').css('pointer-events','none')}else{$('#mobile-clear-property').addClass('active-clear').css('pointer-events','unset')}}else{if($('#prop_search_form input[name="p-type[]"]:checked').length<1){$('#clear-property').removeClass('active-clear').css('pointer-events','none')}else{$('#clear-property').addClass('active-clear').css('pointer-events','unset')}}});$('select[name="min-price"]').on('change',function(){checkAllSearchFilters();if($(this).val()>0){$('#clear-price').addClass('active-clear');$('#mobile-clear-price').addClass('active-clear');$('.clear-selection.all').addClass('active-clearall');$('#clear-price, #mobile-clear-price, .clear-selection.all').css('pointer-events','unset')}else{$('#clear-price').removeClass('active-clear');$('#mobile-clear-price').removeClass('active-clear');$('#clear-price, #mobile-clear-price').css('pointer-events','none')}
min_price_selection=parseInt($(this).children("option:selected").val());max_price_selection=parseInt($(this).parents('.price-options').find('.price-max-range select[name="max-price"]').children("option:selected").val());summary_prices_select(min_price_selection,max_price_selection);$('select[name="max-price"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem<min_price_selection||currentItem==min_price_selection){$(this).hideOption()}})});$('select[name="max-price"]').on('change',function(){checkAllSearchFilters();if($(this).val()>0){$('#clear-price').addClass('active-clear');$('#mobile-clear-price').addClass('active-clear');$('.clear-selection.all').addClass('active-clearall');$('#clear-price, #mobile-clear-price, .clear-selection.all').css('pointer-events','unset')}else{$('#clear-price').removeClass('active-clear');$('#mobile-clear-price').removeClass('active-clear');$('#clear-price, #mobile-clear-price').css('pointer-events','none')}
min_price_selection=parseInt($(this).parents('.price-options').find('.price-min-range select[name="min-price"]').children("option:selected").val());max_price_selection=parseInt($(this).children("option:selected").val());summary_prices_select(min_price_selection,max_price_selection);$('select[name="min-price"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem>max_price_selection){$(this).hideOption()}})});$(document).on("change",'input[name="prop[]"]',function(){checkAllSearchFilters();var isChecked=$(this).prop("checked");if($(this).closest("#prop_search_form")){$('#map_popup_search_form .popUpFilter .property-selection .property-options.select-sec-options ul li input[value="'+$(this).val()+'"]').prop('checked',isChecked)}
if($(this).closest("#map_popup_search_form")){$('#prop_search_form .property-options ul li input[value="'+$(this).val()+'"]').prop('checked',isChecked)}
if($('input[name="prop[]"]:checked').length<1){$('.property-selection .select-sec-options, #property-comm-for-mobile #propertyCommModal .modal-content').find('.clear-selection').removeClass('active-clear').css('pointer-events','none')}else{$('.property-selection .select-sec-options, #property-comm-for-mobile #propertyCommModal .modal-content').find('.clear-selection').addClass('active-clear').css('pointer-events','unset')}
var checkedBoxes=$(this).parents('.property-selection').find('.property-options input[name="prop[]"]:checked').length||$(this).parents('#property-comm-for-mobile').find('#propertyCommModal .property-comm-options input[name="prop[]"]:checked').length;var selected_msg_label="";if(checkedBoxes>0){if(checkedBoxes==1){selected_msg_label=checkedBoxes+' '+property_text}
if(checkedBoxes>1){selected_msg_label=checkedBoxes+' '+properties_text}
$('.property-selection').find('span.search-val').addClass('selected-val').text(selected_msg_label);$('#property-comm-for-mobile .search-fld span.search-val').addClass('selected-val').text(selected_msg_label);$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}else{$('.property-selection').find('span.search-val').removeClass('selected-val').text(all_properties_text);$('#property-comm-for-mobile .search-fld span.search-val').removeClass('selected-val').text(all_properties_text)}});$(document).on('click','.propChoice',function(e){var selected_msg_label="";e.preventDefault();$(this).toggleClass('active');var checkbox=$(this).find('input[type=checkbox]');checkbox.trigger('change');checkbox.attr("checked",checkbox.attr("checked")?!1:!0);if($(this).parents('.filterPanelWrapper').parent().attr('id')=='propertyTyp'){var noOfCheckboxes=$(this).closest('#propertyTyp').find('.propChoice.active').length;$('#prop_search_form .property-type-selection input[value="'+checkbox.val()+'"]').prop('checked',checkbox.prop("checked"));if(noOfCheckboxes>0){if(noOfCheckboxes==1){selected_msg_label=noOfCheckboxes+' '+property_type_text}
if(noOfCheckboxes>1){selected_msg_label=noOfCheckboxes+' '+properties_type_text}
$('#prop_search_form .property-type-selection').find('span.search-val').addClass('selected-val').text(selected_msg_label);$('#property-for-mobile .search-val').addClass('selected-val').text(selected_msg_label);$(this).closest('.filter-panel-details').find('.filter-btns .btn.filter-btn[type=reset]').addClass('active-clear').css('pointer-events','unset');$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}else{$(this).closest('.filter-panel-details').find('.filter-btns .btn.filter-btn[type=reset]').removeClass('active-clear').css('pointer-events','none')}}
if($(this).parents('.filterPanelWrapper').parent().attr('id')=='propertyBeds'){var noOfCheckboxes=$(this).closest('#propertyBeds').find('.propChoice.active').length;$('#prop_search_form .bedroom-selection input[value="'+checkbox.val()+'"]').prop('checked',checkbox.prop("checked"));var bedroomSelectionTxt=summary_bedrooms_select();if(noOfCheckboxes>0){$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset');$(this).closest('.filter-panel-details').find('.filter-btns .btn.filter-btn[type=reset]').addClass('active-clear').css('pointer-events','unset');$('#prop_search_form .bedroom-selection').find('span.search-val').addClass('selected-val').text(bedroomSelectionTxt)}else{$('#prop_search_form .bedroom-selection').find('span.search-val').removeClass('selected-val').text(bedroomSelectionTxt);$(this).closest('.filter-panel-details').find('.filter-btns .btn.filter-btn[type=reset]').removeClass('active-clear').css('pointer-events','none')}}})});var pid="";var desktop_screen_size=window.matchMedia("(min-width: 1025px)");var screen_size=window.matchMedia("(max-width: 1024px)");$('.community-selection label.search-fld').click(function(){pid=$(this).parent().attr("id");if(pid=="community-selection-wrapper"){if(!checkMobile.matches){$('html, body').animate({scrollTop:400},600)}}
$('.price-range-selection .select-sec-options').slideUp();$('.price-range-selection label.search-fld').removeClass("active");$('.property-type-selection .select-sec-options').slideUp();$('.property-type-selection label.search-fld').removeClass("active");$('.bedroom-selection .select-sec-options').slideUp();$('.bedroom-selection label.search-fld').removeClass("active");$('.floor-selection .select-sec-options').slideUp();$('.floor-selection label.search-fld').removeClass("active");$('.area-selection .select-sec-options').slideUp();$('.area-selection label.search-fld').removeClass("active");$('.property-selection .select-sec-options').slideUp();$('.property-selection label.search-fld').removeClass("active");if($(".price-range-selection .select-sec-options").is(":visible")){$('.price-range-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-type-selection .select-sec-options").is(":visible")){$('.property-type-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".bedroom-selection .select-sec-options").is(":visible")){$('.bedroom-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".floor-selection .select-sec-options").is(":visible")){$('.floor-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".area-selection .select-sec-options").is(":visible")){$('.area-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-selection .select-sec-options").is(":visible")){$('.property-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
$('.community-options').slideToggle();$('.community-selection label.search-fld').toggleClass('active');$('.community-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');return!1});$('.bedroom-selection label.search-fld').click(function(){pid=$(this).parent().attr("id");if(pid=="bedroom-selection-wrapper"){if(!checkMobile.matches){$('html, body').animate({scrollTop:400},600)}}
$('.price-range-selection .select-sec-options').slideUp();$('.price-range-selection label.search-fld').removeClass("active");$('.property-type-selection .select-sec-options').slideUp();$('.property-type-selection label.search-fld').removeClass("active");$('.community-options').slideUp();$('.community-selection label.search-fld').removeClass("active");$('.floor-selection .select-sec-options').slideUp();$('.floor-selection label.search-fld').removeClass("active");$('.area-selection .select-sec-options').slideUp();$('.area-selection label.search-fld').removeClass("active");$('.property-selection .select-sec-options').slideUp();$('.property-selection label.search-fld').removeClass("active");if($(".price-range-selection .select-sec-options").is(":visible")){$('.price-range-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-type-selection .select-sec-options").is(":visible")){$('.property-type-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($('.community-options').is(":visible")){$('.community-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".floor-selection .select-sec-options").is(":visible")){$('.floor-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".area-selection .select-sec-options").is(":visible")){$('.area-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
$('.bedroom-selection .select-sec-options').slideToggle();$('.bedroom-selection label.search-fld').toggleClass('active');$('.bedroom-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');return!1});$('.price-range-selection label.search-fld').click(function(){pid=$(this).parent().attr("id");if(pid=="price-range-selection-wrapper"){if(!checkMobile.matches){$('html, body').animate({scrollTop:400},600)}}
$('.bedroom-selection .select-sec-options').slideUp();$('.bedroom-selection label.search-fld').removeClass("active");$('.property-type-selection .select-sec-options').slideUp();$('.property-type-selection label.search-fld').removeClass("active");$(".community-options").hide("fast");$('.community-selection label.search-fld').removeClass("active");$('.floor-selection .select-sec-options').slideUp();$('.floor-selection label.search-fld').removeClass("active");$('.area-selection .select-sec-options').slideUp();$('.area-selection label.search-fld').removeClass("active");$('.property-selection .select-sec-options').slideUp();$('.property-selection label.search-fld').removeClass("active");if($('.community-options').is(":visible")){$('.community-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-type-selection .select-sec-options").is(":visible")){$('.property-type-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".bedroom-selection .select-sec-options").is(":visible")){$('.bedroom-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".floor-selection .select-sec-options").is(":visible")){$('.floor-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".area-selection .select-sec-options").is(":visible")){$('.area-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
$('.price-range-selection .select-sec-options').slideToggle();$('.price-range-selection label.search-fld').toggleClass('active');$('.price-range-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');return!1});$('.property-type-selection label.search-fld').click(function(){var pid=$(this).parent().attr("id");$('.bedroom-selection .select-sec-options').slideUp();$('.bedroom-selection label.search-fld').removeClass("active");$('.price-range-selection .select-sec-options').slideUp();$('.price-range-selection label.search-fld').removeClass("active");$(".community-options").hide("fast");$('.community-selection label.search-fld').removeClass("active");$('.floor-selection .select-sec-options').slideUp();$('.floor-selection label.search-fld').removeClass("active");$('.area-selection .select-sec-options').slideUp();$('.area-selection label.search-fld').removeClass("active");$('.property-selection .select-sec-options').slideUp();$('.property-selection label.search-fld').removeClass("active");if($('.community-options').is(":visible")){$('.community-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".price-range-selection .select-sec-options").is(":visible")){$('.price-range-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".bedroom-selection .select-sec-options").is(":visible")){$('.bedroom-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-type-selection .select-sec-options").is(":visible")){$('.property-type-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".floor-selection .select-sec-options").is(":visible")){$('.floor-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".area-selection .select-sec-options").is(":visible")){$('.area-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
$('.property-type-selection .select-sec-options').slideToggle();$('.property-type-selection label.search-fld').toggleClass('active');$('.property-type-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');return!1});$('.floor-selection label.search-fld').click(function(){var pid=$(this).parent().attr("id");$('.bedroom-selection .select-sec-options').slideUp();$('.bedroom-selection label.search-fld').removeClass("active");$('.price-range-selection .select-sec-options').slideUp();$('.price-range-selection label.search-fld').removeClass("active");$(".community-options").hide("fast");$('.community-selection label.search-fld').removeClass("active");$('.property-type-selection .select-sec-options').slideUp();$('.property-type-selection label.search-fld').removeClass("active");$('.area-selection .select-sec-options').slideUp();$('.area-selection label.search-fld').removeClass("active");$('.property-selection .select-sec-options').slideUp();$('.property-selection label.search-fld').removeClass("active");if($('.community-options').is(":visible")){$('.community-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".price-range-selection .select-sec-options").is(":visible")){$('.price-range-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".bedroom-selection .select-sec-options").is(":visible")){$('.bedroom-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".area-selection .select-sec-options").is(":visible")){$('.area-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-type-selection .select-sec-options").is(":visible")){$('.property-type-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-selection .select-sec-options").is(":visible")){$('.property-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
$('.floor-selection .select-sec-options').slideToggle();$('.floor-selection label.search-fld').toggleClass('active');$('.floor-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');return!1});$('.area-selection label.search-fld').click(function(){var pid=$(this).parent().attr("id");$('.bedroom-selection .select-sec-options').slideUp();$('.bedroom-selection label.search-fld').removeClass("active");$('.price-range-selection .select-sec-options').slideUp();$('.price-range-selection label.search-fld').removeClass("active");$(".community-options").hide("fast");$('.community-selection label.search-fld').removeClass("active");$('.property-type-selection .select-sec-options').slideUp();$('.property-type-selection label.search-fld').removeClass("active");$('.floor-selection .select-sec-options').slideUp();$('.floor-selection label.search-fld').removeClass("active");$('.property-selection .select-sec-options').slideUp();$('.property-selection label.search-fld').removeClass("active");if($('.community-options').is(":visible")){$('.community-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".price-range-selection .select-sec-options").is(":visible")){$('.price-range-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".bedroom-selection .select-sec-options").is(":visible")){$('.bedroom-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-type-selection .select-sec-options").is(":visible")){$('.property-type-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".floor-selection .select-sec-options").is(":visible")){$('.floor-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".property-selection .select-sec-options").is(":visible")){$('.property-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
$('.area-selection .select-sec-options').slideToggle();$('.area-selection label.search-fld').toggleClass('active');$('.area-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');return!1});$('.property-selection label.search-fld').click(function(){var pid=$(this).parent().attr("id");$('.bedroom-selection .select-sec-options').slideUp();$('.bedroom-selection label.search-fld').removeClass("active");$('.price-range-selection .select-sec-options').slideUp();$('.price-range-selection label.search-fld').removeClass("active");$(".community-options").hide("fast");$('.community-selection label.search-fld').removeClass("active");$('.property-type-selection .select-sec-options').slideUp();$('.property-type-selection label.search-fld').removeClass("active");$('.floor-selection .select-sec-options').slideUp();$('.floor-selection label.search-fld').removeClass("active");$('.area-selection .select-sec-options').slideUp();$('.area-selection label.search-fld').removeClass("active");if($('.community-options').is(":visible")){$('.community-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".price-range-selection .select-sec-options").is(":visible")){$('.price-range-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".bedroom-selection .select-sec-options").is(":visible")){$('.bedroom-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".floor-selection .select-sec-options").is(":visible")){$('.floor-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
if($(".area-selection .select-sec-options").is(":visible")){$('.area-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down')}
$('.property-selection .select-sec-options').slideToggle();$('.property-selection label.search-fld').toggleClass('active');$('.property-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');return!1});function summary_bedrooms_select(){var bedrooms_dropdown_array=[];var bedrooms_dropdown_string="";var single_string="";var i=0;$.each($('#prop_search_form input[name="bed[]"]:checked, #prop_search_mobile_form input[name="bed[]"]:checked'),function(){single_string=$(this).attr('id').match(/\d+/);if(single_string=="5")
single_string=single_string+'+';if(single_string!=''&&single_string!=null){bedrooms_dropdown_array.push(single_string)}});bedrooms_dropdown_string=bedrooms_dropdown_array.join(", ");if($('#gform_16').length>0){$('#gform_16 #input_16_46').val(bedrooms_dropdown_string)}
if(bedrooms_dropdown_string==""){bedrooms_dropdown_string=any_text}else{if(bedrooms_dropdown_string=='1'){bedrooms_dropdown_string=bedrooms_dropdown_array+' '+bedroom_text}else{bedrooms_dropdown_string=bedrooms_dropdown_array+' '+bedrooms_text}
bedrooms_dropdown_string=bedrooms_dropdown_string.replace(/,/g,", ")}
return(bedrooms_dropdown_string)}
function summary_prices_select(min_price_selection,max_price_selection){selectedPriceRange=currency_text+' '+parseInt(min_price_selection).toLocaleString()+' - '+parseInt(max_price_selection).toLocaleString();$('.price-range-selection').find('span.search-val').addClass('selected-val').text(selectedPriceRange);$('#price-for-mobile .search-val').addClass('selected-val').text(selectedPriceRange);if($('#gform_16').length>0){$('#gform_16 #input_16_47').val(selectedPriceRange)}}
function summary_floors_select(floorLevel){if(floorLevel>0){$('.clear-selection.all').addClass('active-clearall');$('#clear-floor-mobile, #clear-floor').addClass('active-clear');$('.floor-selection, #floor-for-mobile').find('span.search-val').addClass('selected-val').text(floorLevel);$('#clear-floor-mobile, #clear-floor, .clear-selection.all').css('pointer-events','unset')}else{$('#clear-floor').removeClass('active-clear').css('pointer-events','none');$('.floor-selection, #floor-for-mobile').find('span.search-val').removeClass('selected-val').text(all_text)}
if(floorLevel==0){$('.floor-selection, #floor-for-mobile').find('span.search-val').removeClass('selected-val').text(all_text)}}
function summary_area_select(minArea,maxArea){$('select[name="min-area"]').val(minArea);$('select[name="max-area"]').val(maxArea);if(minArea>0||maxArea<50000){$('.clear-selection.all').addClass('active-clearall');$('#clear-area, #clear-area-mobile').addClass('active-clear');$('#clear-area, #clear-area-mobile, .clear-selection.all').css('pointer-events','unset')}else{$('#clear-area, #clear-area-mobile').removeClass('active-clear');$('#clear-area, #clear-area-mobile').css('pointer-events','none')}
if($('select[name="min-area"]').val()==0&&$('select[name="max-area"]').val()==50000){$('.area-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('#area-for-mobile span.search-val').removeClass('selected-val').text(any_text)}else{var selectedAreaRange=parseInt(minArea)+' '+sqft_text+' - '+parseInt(maxArea)+' '+sqft_text;$('.area-selection').find('span.search-val').addClass('selected-val').text(selectedAreaRange);$('#area-for-mobile span.search-val').addClass('selected-val').text(selectedAreaRange)}}
$(document).on("click",".clear-selection",function(e){$(this).removeClass('active-clear');$(this).css('pointer-events','none');selected_id=$(this).attr("id");if(selected_id=='clear-community'||selected_id=='clear-map-community'||selected_id=='clear-all-fields'){$('input[name="comm[]"]:checkbox').prop('checked',!1);$('input[name="prop[]"]:checkbox').prop('checked',!1);$('.community-selection').find('span.search-val').removeClass('selected-val').text(all_communities_text);$('.property-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('.property-selection .select-sec-options .clear-selection').removeClass('active-clear').css('pointer-events','none');$('.community-selection .select-sec-options .clear-selection').removeClass('active-clear').css('pointer-events','none');$('.community-selection').siblings('.community-options.select-sec-options').find('.clear-selection').removeClass('active-clear').css('pointer-events','none')}
if(selected_id=='mobile-clear-community'||selected_id=='clear-all-fields'){$('#communityModal input[name="comm[]"]:checkbox').prop('checked',!1);$('#propertyCommModal input[name="prop[]"]:checkbox').prop('checked',!1);$('#community-for-mobile span.search-val').removeClass('selected-val').text(all_communities_text);$('#property-comm-for-mobile span.search-val').removeClass('selected-val').text(any_text);$('#property-comm-for-mobile .property-selection .modal-content .filter-bottom .clear-selection').removeClass('active-clear').css('pointer-events','none')}
if(selected_id=='clear-bedrooms'||selected_id=='clear-all-fields'){$('#prop_search_form input[name="bed[]"]:checkbox').prop('checked',!1);$('.bedroom-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('#map_search_form #propertyBeds .propChoice input[name="bed[]"]:checkbox').parent().removeClass('active');$('#map_search_form #propertyBeds .propChoice input[name="bed[]"]:checkbox').attr('checked',!1);if($('#map_search_form #propertyBeds .propChoice.active').length<1){$('#map_search_form #propertyBeds').siblings('a.filtrBtn').removeClass('active')}else{$('#map_search_form #propertyBeds').siblings('a.filtrBtn').addClass('active')}
$('.bedroom-selection .select-sec-options .clear-selection').removeClass('active-clear').css('pointer-events','none');$('#map_search_form #propertyBeds .filter-panel-details .filter-btns .filter-btn[type=reset]').removeClass('active-clear').css('pointer-events','none')}
if(selected_id=='mobile-clear-bedrooms'){$('#bedroomsModal input[name="bed[]"]:checkbox').prop('checked',!1);$('#bedroom-for-mobile span.search-val').removeClass('selected-val').text(any_text)}
if(selected_id=='clear-price'||selected_id=='mobile-clear-price'||selected_id=='clear-all-fields'){$('select[name="min-price"] option').showOption();$('select[name="max-price"] option').showOption();$('select[name="min-price"] option[value="0"]').prop("selected",!0);$('select[name="max-price"] option[value="100000000"]').prop("selected",!0);$('#priceModal select[name="min-price"] option[value="0"]').prop("selected",!0);$('#priceModal select[name="max-price"] option[value="100000000"]').prop("selected",!0);$('.price-range-selection, #price-for-mobile').find('span.search-val').removeClass('selected-val').text(any_text)}
if(selected_id=='clear-property'||selected_id=='clear-all-fields'){$('input[name="p-type[]"]:checkbox').prop('checked',!1);$('.property-type-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('#map_search_form #propertyTyp .propChoice input[name="p-type[]"]:checkbox').parent().removeClass('active');$('#map_search_form #propertyTyp .propChoice input[name="p-type[]"]:checkbox').attr('checked',!1);if($('#map_search_form #propertyTyp .propChoice.active').length<1){$('#map_search_form #propertyTyp').siblings('a.filtrBtn').removeClass('active')}else{$('#map_search_form #propertyTyp').siblings('a.filtrBtn').addClass('active')}
$('.community-options-desktop').html(CommunityDDBeforeAJax);$('.primary-communitylist-container').removeClass('property-community-list');if($(this).closest('.prop_search_form').parent().hasClass('home-search-component')){$('.community-selection').find('span.search-val').removeClass('selected-val').text(all_communities_text)}
$('.property-type-selection .select-sec-options .clear-selection').removeClass('active-clear').css('pointer-events','none');$('#map_search_form #propertyTyp .filter-panel-details .filter-btns .filter-btn[type=reset]').removeClass('active-clear').css('pointer-events','none')}
if(selected_id=='mobile-clear-property'){$('#property-for-mobile .search-val').removeClass('selected-val').text(any_text);$('#propertyTypeModal input[name="p-type[]"]:checkbox').prop('checked',!1);$('.community-options-mobile').html(CommunityDDBeforeAJax);if($(this).closest('.prop-search-mobile-form').parent().attr('id')=='prop_search_mobile_form'){$('#community-for-mobile span.search-val').removeClass('selected-val').text(all_communities_text)}
$('#mobile-clear-community').removeClass('active-clear')}
if(selected_id=='clear-floor'||selected_id=='clear-floor-mobile'||selected_id=='clear-all-fields'){$('select[name="floor"] option[value="All"]').prop("selected",!0);$('.floor-selection, #floor-for-mobile').find('span.search-val').removeClass('selected-val').text(any_text);$('.floor-selection .select-sec-options .clear-selection').removeClass('active-clear').css('pointer-events','none')}
if(selected_id=='clear-area'||selected_id=='clear-area-mobile'||selected_id=='clear-all-fields'){$('select[name="min-area"] option').showOption();$('select[name="max-area"] option').showOption();$('select[name="min-area"] option[value="0"]').prop("selected",!0);$('select[name="max-area"] option[value="50000"]').prop("selected",!0);$('#clear-area-mobile').removeClass('active-clear').css('pointer-events','none');$('.area-selection, #area-for-mobile').find('span.search-val').removeClass('selected-val').text(any_text);$('.area-selection .select-sec-options .clear-selection').removeClass('active-clear').css('pointer-events','none')}
if(selected_id=='clear-comm-property'||selected_id=='clear-all-fields'){$('input[name="prop[]"]:checkbox').prop('checked',!1);$('.property-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('.property-selection, #property-comm-for-mobile').find('span.search-val').removeClass('selected-val').text(all_properties_text);$('.property-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('.property-selection .select-sec-options .clear-selection').removeClass('active-clear').css('pointer-events','none')}
if(selected_id=='clear-all-fields'){$('#clear-all-fields').removeClass('active-clearall')}
if($('.clear-selection.active-clear').length<0){$('#clear-all-fields').removeClass('active-clearall')}
checkAllSearchFilters()});$('#prop_search_form input[name="bed[]"], #prop_search_mobile_form input[name="bed[]"]').on('change',function(){var bedrooms_dropdown_string1=summary_bedrooms_select();if($('input[name="bed[]"]:checked').length>0){$('.bedroom-selection').find('span.search-val').addClass('selected-val').text(bedrooms_dropdown_string1);$('#bedroom-for-mobile .search-val').addClass('selected-val').text(bedrooms_dropdown_string1);$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset')}else{$('.bedroom-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('#bedroom-for-mobile .search-val').removeClass('selected-val').text(any_text)}});$('#prop_search_form ul li input[name="comm[]"], #map_popup_search_form .popUpFilter .community-selection .community-options.select-sec-options ul li input[name="comm[]"], .homesearch_mobile_filter .prop-search-mobile-form #communityModal .community-options.select-sec-options ul li input[name="comm[]"]').on('change',function(){var checkedBoxes=$(this).parents('#prop_search_form').find('input[name="comm[]"]:checked').length||$(this).parents('.community-selection').find('.community-options.select-sec-options input[name="comm[]"]:checked').length||$(this).parents('.community-options-mobile').find('input[name="comm[]"]:checked').length;var selected_msg_label="";var isChecked=$(this).prop("checked");if($(this).closest("#prop_search_form")){$('#map_popup_search_form .popUpFilter .community-selection .community-options.select-sec-options ul li input[value="'+$(this).val()+'"]').prop('checked',isChecked)}
if($(this).closest("#map_popup_search_form")){$('#prop_search_form .community-options ul li input[value="'+$(this).val()+'"]').prop('checked',isChecked)}
if(checkedBoxes>0){if(checkedBoxes==1){selected_msg_label=checkedBoxes+' '+community_text}
if(checkedBoxes>1){selected_msg_label=checkedBoxes+' '+communities_text}
$('input[name="comm[]"]').parents('.community-options.select-sec-options').siblings('.community-selection').find('span.search-val').addClass('selected-val').text(selected_msg_label);$('input[name="comm[]"]').closest('.community-options.select-sec-options').parents('.community-selection').find('span.search-val').addClass('selected-val').text(selected_msg_label);$('#community-for-mobile .search-val').addClass('selected-val').text(selected_msg_label);$('.clear-selection.all').addClass('active-clearall').css('pointer-events','unset');$('.community-selection .select-sec-options, #property-comm-for-mobile #propertyCommModal .modal-content').find('.clear-selection').addClass('active-clear').css('pointer-events','unset')}else{$('input[name="comm[]"]').parents('.community-options.select-sec-options').siblings('.community-selection').find('span.search-val').removeClass('selected-val').text(all_communities_text);$('input[name="comm[]"]').closest('.community-options.select-sec-options').parents('.community-selection').find('span.search-val').removeClass('selected-val').text(all_communities_text);$('#community-for-mobile .search-val').removeClass('selected-val').text(all_communities_text);$('.community-selection .select-sec-options, #property-comm-for-mobile #propertyCommModal .modal-content').find('.clear-selection').addClass('active-clear').css('pointer-events','unset')}
var sel_comm=[];if($(this).parents('#prop_search_form').length>0){$(this).parents('#prop_search_form').find('input[name="comm[]"]:checked').each(function(){sel_comm.push(this.value)});getPropertiesByCommunities(sel_comm,$(this).parents('#prop_search_form'))}
if($(this).parents('#map_popup_search_form').length>0){$(this).parents('#map_popup_search_form').find('.community-options.select-sec-options input[name="comm[]"]:checked').each(function(){sel_comm.push(this.value)});getPropertiesByCommunities(sel_comm,$(this).parents('#map_popup_search_form'))}});function getPropertiesByCommunities(communities=null,objElement){$('.property-selection').find('span.search-val').removeClass('selected-val').text(any_text);$('.property-selection').find('.emaarspinner').removeClass('d-none');var jqXHR=jQuery.ajax({type:"POST",url:emaar_ajax_script.ajaxurl,data:{action:'get_properties_by_communities',comm:communities,},success:function(data){data=data.replace(/\\n/g,"\\n").replace(/\\'/g,"\\'").replace(/\\"/g,'\\"').replace(/\\&/g,"\\&").replace(/\\r/g,"\\r").replace(/\\t/g,"\\t").replace(/\\b/g,"\\b").replace(/\\f/g,"\\f");data=data.replace(/[\u0000-\u0019]+/g,"");data=JSON.parse(data);if(data.message=='success'){var htmlMobilePropertiesList='';var htmlPropertiesList='';var htmlPropertiesMap='';$.each(data.data.properties_list,function(key,value){htmlMobilePropertiesList+='<li><input type="checkbox" id="m-prop-'+key+'" name="prop[]" value="'+value.SF_SLUG+'"><label for="m-prop-'+key+'">'+value.TITLE+'</label><br></li>';htmlPropertiesList+='<li><input type="checkbox" id="d-prop-'+key+'" name="prop[]" value="'+value.SF_SLUG+'"><label for="d-prop-'+key+'">'+value.TITLE+'</label><br></li>';htmlPropertiesMap+='<li><input type="checkbox" id="d-prop-map-'+key+'" name="prop[]" value="'+value.SF_SLUG+'"><label for="d-prop-map-'+key+'">'+value.TITLE+'</label><br></li>'});if(htmlPropertiesList.length>0){$('#prop_search_form .property-options ul').html(htmlPropertiesList);$('#map_popup_search_form .property-options ul').html(htmlPropertiesMap);$('div.property-comm-options ul').html(htmlMobilePropertiesList)}}else{$('.property-options ul').html('<li>'+no_property_text+'</li>')}
$('.property-selection').find('.emaarspinner').addClass('d-none')},error:function(jqXHR,textStatus,errorThrown){}});return jqXHR.responseText}
$(document).on('click','.prop-search-bar input[name="comm[]"]',function(){var checkedBoxes=$('.prop-search-bar input[name="comm[]"]:checked').length;var selected_msg_label="";if(checkedBoxes>0){if(checkedBoxes==1){selected_msg_label=checkedBoxes+' '+community_text}
if(checkedBoxes>1){selected_msg_label=checkedBoxes+' '+communities_text}
$('.community-selection').find('span.search-val').addClass('selected-val').text(selected_msg_label);$('#community-for-mobile .search-val').addClass('selected-val').text(selected_msg_label);$('#clear-community').addClass('active-clear').css('pointer-events','unset');if(checkMobile.matches){$('#mobile-clear-community').addClass('active-clear').css('pointer-events','unset')}}else{$('.community-selection').find('span.search-val').removeClass('selected-val').text(all_communities_text);$('#clear-community').removeClass('active-clear').css('pointer-events','none');if(checkMobile.matches){$('#mobile-clear-community').removeClass('active-clear').css('pointer-events','none')}}
var sel_comm=[];if($(this).parents('div.prop-search-mobile-form').length>0){$(this).parents('div.prop-search-mobile-form').find('input[name="comm[]"]:checked').each(function(){sel_comm.push(this.value)});getPropertiesByCommunities(sel_comm,$(this).parents('div.prop-search-mobile-form'))}});$(document).on('click','.home-search-component #clear-community',function(){$('.home-search-component input[name="comm[]"]:checkbox').prop('checked',!1);$('.community-selection').find('span.search-val').removeClass('selected-val').text(all_communities_text);$('#clear-community').removeClass('active-clear').css('pointer-events','none')});$('#priceModal select[name="min-price"]').on('change',function(){if($('#priceModal select[name="min-price"]').val()==0&&$('#priceModal select[name="max-price"]').val()==100000000){}else{selectedPriceRange=currency_text+' '+parseInt($('#priceModal select[name="min-price"]').val()).toLocaleString()+' - '+parseInt($('#priceModal select[name="max-price"]').val()).toLocaleString();$('#price-for-mobile .search-val').addClass('selected-val').text(selectedPriceRange);$('#mobile-clear-price').addClass('active-clear').css('pointer-events','unset')}});$('select[name="max-price-mobile"]').on('change',function(){summary_prices_select()});$('#mobile-bedrooms-apply').click(function(){var bedrooms_dropdown_string1=summary_bedrooms_select();$('#bedroomsModal').hide();$('#btn-show-filters').hide();$('.homepage-mobile-filter-section #prop_search_mobile_form').show();if($('input[name="bed[]"]:checked').length>0){$('#bedroom-for-mobile .search-val').addClass('selected-val').text(bedrooms_dropdown_string1)}else{$('#bedroom-for-mobile .search-val').removeClass('selected-val').text(any_text)}});$('#mobile-community-apply').click(function(){$('#communityModal').hide();$('#btn-show-filters').hide();$('.homepage-mobile-filter-section #prop_search_mobile_form').show();var checkedBoxes=$('input[name="comm[]"]:checked').length;var selected_msg_label="";if(checkedBoxes>0){if(checkedBoxes==1){selected_msg_label=checkedBoxes+' '+community_text}
if(checkedBoxes>1){selected_msg_label=checkedBoxes+' '+communities_text}
$('#community-for-mobile .search-val').addClass('selected-val').text(selected_msg_label)}else{$('#community-for-mobile .search-val').removeClass('selected-val').text(all_communities_text)}});$('#mobile-price-apply').click(function(){$('#priceModal').hide();$('#btn-show-filters').hide();$('.homepage-mobile-filter-section #prop_search_mobile_form').show();var min_price_mobile=$('#priceModal select[name="min-price"]').val();var max_price_mobile=$('#priceModal select[name="max-price"]').val();if(min_price_mobile==0&&max_price_mobile==100000000){selectedPriceRange=any_text;$('#price-for-mobile .search-val').removeClass('selected-val').text(selectedPriceRange)}else{selectedPriceRange=currency_text+' '+parseInt(min_price_mobile).toLocaleString()+' - '+parseInt(max_price_mobile).toLocaleString();$('#price-for-mobile .search-val').addClass('selected-val').text(selectedPriceRange)}});$('#priceModal select[name="max-price"]').on('change',function(){if($(this).val()>0){$('#mobile-clear-price').addClass('active-clear').css('pointer-events','unset')}else{$('#mobile-clear-price').removeClass('active-clear').css('pointer-events','none')}
max_price_selection=parseInt($(this).children("option:selected").val());$('#priceModal select[name="min-price"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem>max_price_selection){$(this).hideOption()}})});$('#priceModal select[name="min-price"]').on('change',function(){if($(this).val()>0){$('#mobile-clear-price').addClass('active-clear').css('pointer-events','unset')}else{$('#mobile-clear-price').removeClass('active-clear').css('pointer-events','none')}
min_price_selection=parseInt($(this).children("option:selected").val());$('#priceModal select[name="max-price"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem<min_price_selection){$(this).hideOption()}})});$('select[class="max-select"]').on('change',function(){checkAllSearchFilters();if($(this).val()>0){$(this).parents('.select-sec-options').find('.clear-selection').addClass('active-clear');$(this).parents('.select-sec-options').find('.clear-selection.active-clear').css('pointer-events','unset')}else{$(this).parents('.select-sec-options').find('.clear-selection').removeClass('active-clear');$(this).parents('.select-sec-options').find('.clear-selection.active-clear').css('pointer-events','none')}
max_selection=parseInt($(this).children("option:selected").val());var topTwo=$(this).parents().eq(1).attr('class');topTwo='.'+topTwo.split(/\s(.+)/)[0]+" ";$(topTwo+'select[class="min-select"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem>max_selection){$(this).hideOption()}})});$('select[class="min-select"]').on('change',function(){checkAllSearchFilters();if($(this).val()>0){$(this).parents('.select-sec-options').find('.clear-selection').addClass('active-clear');$(this).parents('.select-sec-options').find('.clear-selection.active-clear').css('pointer-events','unset')}else{$(this).parents('.select-sec-options').find('.clear-selection').removeClass('active-clear');$(this).parents('.select-sec-options').find('.clear-selection.active-clear').css('pointer-events','none')}
min_selection=parseInt($(this).children("option:selected").val());var topTwo=$(this).parents().eq(1).attr('class');topTwo='.'+topTwo.split(/\s(.+)/)[0]+" ";$(topTwo+'select[class="max-select"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem<min_selection||currentItem==min_selection){$(this).hideOption()}})});$('select[name="floor"]').on('change',function(){checkAllSearchFilters();summary_floors_select($(this).children("option:selected").val())});$('select[name="min-area"]').on('change',function(){checkAllSearchFilters();var min_area_selection=parseInt($(this).children("option:selected").val());var max_area_selection=parseInt($(this).parents('.area-options').find('.area-max-range select[name="max-area"]').children("option:selected").val());summary_area_select(min_area_selection,max_area_selection)});$('select[name="max-area"]').on('change',function(){checkAllSearchFilters();var min_area_selection=parseInt($(this).parents('.area-options').find('.area-min-range select[name="min-area"]').children("option:selected").val());var max_area_selection=parseInt($(this).children("option:selected").val());summary_area_select(min_area_selection,max_area_selection)});$(document).click(function(evt){evt.stopPropagation();var propContainer=$(".home-search-component .property-type-options");var bedsContainer=$(".home-search-component .bedroom-options, .property-alert-select .bedroom-selection .bedroom-options");var przContainer=$(".home-search-component .price-options, .property-alert-select .price-range-selection .price-options");var commContainer=$(".home-search-component .community-options, .property-alert-select .community-options");if(propContainer!==evt.target&&!propContainer.has(evt.target).length&&$(propContainer).is(':visible')){$('.property-type-selection label.search-fld').removeClass("active");$('.property-type-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');$('.property-type-options').slideUp()}
if(bedsContainer!==evt.target&&!bedsContainer.has(evt.target).length&&$(bedsContainer).is(':visible')){$('.bedroom-selection label.search-fld').removeClass("active");$('.bedroom-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');$('.bedroom-options').slideUp()}
if(przContainer!==evt.target&&!przContainer.has(evt.target).length&&$(przContainer).is(':visible')){$('.price-range-selection label.search-fld').removeClass("active");$('.price-range-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');$('.price-options').slideUp()}
if(commContainer!==evt.target&&!commContainer.has(evt.target).length&&$(commContainer).is(':visible')){$('.community-selection label.search-fld').removeClass("active");$('.community-selection label.search-fld i.dropdown-icon').toggleClass('fa-angle-up fa-angle-down');$('.community-options').slideUp()}});function initRYIF_1(){var checkNumber=!1;$('#gform_1 #field_1_6.phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_1 #field_1_6.phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_1 #gfield_description_1_6 .phone-mask').html(selectedCountry)});$('#gform_1 #gfield_description_1_6 .phone-mask').html($('#gform_1 #field_1_6.phone-intl-code select').val())}
function initRYIF_4(){$('#gform_6 #field_6_32.phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_6 #field_6_32.phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_6 #gfield_description_6_32 .phone-mask').html(selectedCountry)});$('#gform_6 #gfield_description_6_32 .phone-mask').html($('#gform_6 #field_6_32.phone-intl-code select').val());$('#gform_6 #field_6_6.booking-phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_6 #field_6_6.booking-phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_6 #gfield_description_6_6 .phone-mask').html(selectedCountry)});$('#gform_6 #gfield_description_6_6 .phone-mask').html($('#gform_6 #field_6_6.booking-phone-intl-code select').val())}
function initRYIF_12(){$('#gform_12 #field_12_6.booking-phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_12 #field_12_6.booking-phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_12 #gfield_description_12_6 .phone-mask').html(selectedCountry)});$('#gform_12 #gfield_description_12_6 .phone-mask').html($('#gform_12 #field_12_6.booking-phone-intl-code select').val())}
function initRYIF_13(){$('#gform_13 #field_13_6.phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_13 #field_13_6.phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_13 #gfield_description_13_6 .phone-mask').html(selectedCountry)});$('#gform_13 #gfield_description_13_6 .phone-mask').html($('#gform_13 #field_13_6.phone-intl-code select').val())}
function initRYIF_16(){var checkNumber=!1;$('#gform_16 #field_16_6.phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_16 #field_16_6.phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_16 #gfield_description_16_6 .phone-mask').html(selectedCountry)});$('#gform_16 #gfield_description_16_6 .phone-mask').html($('#gform_16 #field_16_6.phone-intl-code select').val())}
function initRYIF_8(){$('#gform_8 #field_8_17.phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_8 #field_8_17.phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_8 #gfield_description_8_17 .phone-mask').html(selectedCountry)});$('#gform_8 #gfield_description_8_17 .phone-mask').html($('#gform_8 #field_8_17.phone-intl-code select').val())}
function initRYIF_14(){$('#gform_14 #field_14_32.phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_14 #field_14_32.phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_14 #gfield_description_14_32 .phone-mask').html(selectedCountry)});$('#gform_14 #gfield_description_14_32 .phone-mask').html($('#gform_14 #field_14_32.phone-intl-code select').val());$('#gform_14 #field_14_6.booking-phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_14 #field_14_6.booking-phone-intl-code select').change(function(){var selectedCountry=$(this).children("option:selected").val();$('#gform_14 #gfield_description_14_6 .phone-mask').html(selectedCountry)});$('#gform_14 #gfield_description_14_6 .phone-mask').html($('#gform_14 #field_14_6.booking-phone-intl-code select').val())}
function gfromFilterSpecialCharacters(){$('.gform_wrapper div.ginput_container_email input').on('input',function(e){var c=this.selectionStart,r=/[~`!#$%\^&*()+=\[\]\\';,/{}|\\": <>\?]/gi,v=$(this).val();if(r.test(v)){$(this).val(v.replace(r,''));c--}
this.setSelectionRange(c,c)});$('.gform_wrapper input[type=text], .gform_wrapper textarea').on('input',function(e){var c=this.selectionStart,r=/  /gi,v=$(this).val();if(r.test(v)){$(this).val(v.replace(r,' '));c--}
this.setSelectionRange(c,c)})}
jQuery(document).on('gform_post_render',function(event,form_id,current_page){if($('div.validation_error').length>0){if(typeof formName!=='undefined'){setFormName(formName)}}
if($('#gform_1').length>0&&form_id==1){initRYIF_1()}
if($('#gform_16').length>0&&form_id==16){initRYIF_16();if($('div.validation_error').length>0){$(".booking-overlay").hide()}}
if($('#gform_6').length>0&&form_id==6){initRYIF_4();if($('div.validation_error').length>0){$(".booking-overlay").hide()}}
if($('#gform_14').length>0&&form_id==14){initRYIF_14();if($('div.validation_error').length>0){$(".booking-overlay").hide()}}
if($('#gform_8').length>0&&form_id==8){initRYIF_8();if($('div.validation_error').length>0){var hashLink=window.location.hash;if(hashLink&&hashLink=='#investor-enquiries'){$('#gform_8 select#input_8_15').css('pointer-events','none');$('#gform_8 select#input_8_15').val('Investor Enquiries');$('#gform_8 select#input_8_15 option:not(:selected)').remove()}}}
if($('#gform_12').length>0&&form_id==12){initRYIF_12();if($('div.validation_error').length>0){$(".booking-overlay").hide();var selectedValueDate=jQuery("#input_12_9").val();var getDateTimeArray=selectedValueDate.split("_");var getDateTime=getDateTimeArray[5];var JSONObject=JSON.parse(getDateTime);var now=new Date();var timeSlot={};$.each(JSONObject,function(keyDate,valueDateTime){var preferredDate=keyDate;timeSlot=valueDateTime;jQuery('#input_12_10').html('<option value="">Select time</option>');$.each(timeSlot,function(key,value){jQuery('#input_12_10').append('<option value="'+value+'">'+value+'</option>')})});var h_preftime=$('#input_12_15').val();$("#input_12_10 option[value='"+h_preftime+"']").prop("selected",!0)}}
if($('#gform_13').length>0&&form_id==13){initRYIF_13();if($('div.validation_error').length>0){$(".booking-overlay").hide()}}
gfromFilterSpecialCharacters()});initRYIF_1();initRYIF_4();initRYIF_12();initRYIF_13();initRYIF_8();initRYIF_14();initRYIF_16();gfromFilterSpecialCharacters();$("#gform_fields_1 .ginput_container_email #input_1_2").attr('maxlength','80');$("#gform_fields_2 .ginput_container_email #input_2_1").attr('maxlength','80');$('#gform_submit_button_6').click(function(){$(".booking-overlay").show()});$('#gform_submit_button_14').click(function(){$(".booking-overlay").show()});$('#gform_submit_button_17').click(function(){$(".booking-overlay").show()});$('#gform_next_button_17_59').click(function(){$(".booking-overlay").show()});$('#gform_previous_button_17').click(function(){$(".booking-overlay").show()});$('#gform_submit_button_12').click(function(){$(".booking-overlay").show()});$(document).on("click","#gform_submit_button_16",function(){$(".booking-overlay").show()});window.ryiv_form_introduction;window.formName;window.brochureTriggeredLead;$(document).on("click",".get-touch-btn",function(){formName=$(this).attr('data-formname');setFormName(formName);if($(this).hasClass('brochure-upload')){brochureTriggeredLead=!0}else{brochureTriggeredLead=!1}});function setFormName(formName){if(formName!=''){$('#input_1_24').val(formName);var ryi=$('#registerModal').attr('data-ryi');var git=$('#registerModal').attr('data-git');var ryiv=$('#registerModal').attr('data-ryiv');var rypi=$('#registerModal').attr('data-rypi');var pbu=$('#registerModal').attr('data-pbu');if(formName=='Register your Interest'){$('#registerModal .gform_heading .gform_title').text(ryi);$('.schedule-call-info').text("")}else if(formName=='Get in Touch'){if(git!='')
$('#registerModal .gform_heading .gform_title').text(git);$('.schedule-call-info').text("")}else if(formName=='Register Interest'){if(rypi!='')
$('#registerModal .gform_heading .gform_title').text(rypi);$('.schedule-call-info').text("")}else if(formName=='Schedule A Call'){if(ryiv!='')
$('#registerModal .gform_heading .gform_title').text(ryiv);$('.schedule-call-info').text(ryiv_form_introduction)}else if(formName=='Pre-Book Your Unit'){$('#registerModal .gform_heading .gform_title').text(pbu)}}}});
/*! contentloaded.min.js - https://github.com/dperini/ContentLoaded - Author: Diego Perini - License: MIT */
function contentLoaded(b,i){var j=!1,k=!0,a=b.document,l=a.documentElement,f=a.addEventListener,h=f?'addEventListener':'attachEvent',n=f?'removeEventListener':'detachEvent',g=f?'':'on',c=function(d){if(d.type=='readystatechange'&&a.readyState!='complete')return;(d.type=='load'?b:a)[n](g+d.type,c,!1);if(!j&&(j=!0))i.call(b,d.type||d)},m=function(){try{l.doScroll('left')}catch(e){setTimeout(m,50);return}c('poll')};if(a.readyState=='complete')i.call(b,'lazy');else{if(!f&&l.doScroll){try{k=!b.frameElement}catch(e){}if(k)m()}a[h](g+'DOMContentLoaded',c,!1);a[h](g+'readystatechange',c,!1);b[h](g+'load',c,!1)}}
function setCookie(name,value,days){var expires="";if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));expires="; expires="+date.toUTCString()}
var secure=location.protocol==='https:'?'; secure':'';var httpOnly='; HttpOnly';document.cookie=name+"="+(value||"")+expires+"; path=/"+secure}
function getCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length)}
return null}
function eraseCookie(name){document.cookie=name+'=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;'}
function getRefQueryParam(name){name=name.replace(/[\[]/,'\\[').replace(/[\]]/,'\\]');var regex=new RegExp('[\\?&]'+name+'=([^&#]*)');var results=regex.exec(location.search);return results===null?null:decodeURIComponent(results[1].replace(/\+/g,' '))};function getUTMsFromQueryParam(){return{utm_source:getRefQueryParam("utm_source")||'',utm_medium:getRefQueryParam("utm_medium")||'',utm_content:getRefQueryParam("utm_content")||'',utm_campaign:getRefQueryParam("utm_campaign")||'',utm_term:getRefQueryParam("utm_term")||''}}
function persistUTMs(){if(getRefQueryParam("utm_source")||getRefQueryParam("utm_medium")||getRefQueryParam("utm_content")||getRefQueryParam("utm_campaign")||getRefQueryParam("utm_term")){setCookie('emr_utms',JSON.stringify(getUTMsFromQueryParam()),7)}}
function getUTMs(){var emr_utms={};try{emr_utms=JSON.parse(getCookie("emr_utms"))||{}}catch(e){};return(emr_utms&&(typeof emr_utms==="object")&&emr_utms.hasOwnProperty("utm_source"))?emr_utms:getUTMsFromQueryParam()}
function getUTMSV2(){var emr_utms={};try{emr_utms=JSON.parse(getCookie("emr_utms"))||{}}catch(e){};return(emr_utms&&(typeof emr_utms==="object")&&emr_utms.hasOwnProperty("utm_source"))?emr_utms:getUTMsFromQueryParam()}
contentLoaded(window,persistUTMs);function replaceUrlParam(url,paramName,paramValue){if(paramValue==null){paramValue=''}
var pattern=new RegExp('\\b('+paramName+'=).*?(&|#|$)');if(url.search(pattern)>=0){return url.replace(pattern,'$1'+paramValue+'$2')}
url=url.replace(/[?#]$/,'');return url+(url.indexOf('?')>0?'&':'?')+paramName+'='+paramValue}
function removeURLParameter(url,parameter){var urlparts=url.split('?');if(urlparts.length>=2){var prefix=encodeURIComponent(parameter)+'=';var pars=urlparts[1].split(/[&;]/g);for(var i=pars.length;i-->0;){if(pars[i].lastIndexOf(prefix,0)!==-1){pars.splice(i,1)}}
return urlparts[0]+(pars.length>0?'?'+pars.join('&'):'')}
return url}
$(".gform_button").click(function(){if($(this).attr('data-init')=='Y')
return;$(this).attr('data-init','Y')});$(document).on("click",".gform_button",function(){});function isHidden(el){return(el.offsetParent===null)}
function isEmail(email){var regex=/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;return regex.test(email)}
window.getInTouchEmail;window.newsAndOffers;$('#gform_1').submit(function(){setTimeout(function(){$('.gform_ajax_spinner').show();getInTouchEmail=$('#input_1_2').val()},600);if($('#choice_1_9_1').is(':checked')){newsAndOffers=!0}else{newsAndOffers=!1}});jQuery(document).bind("gform_confirmation_loaded",function(event,form_id){if(form_id==1&&formName=='Schedule A Call'){let params=new URLSearchParams(getUTMSV2());let keysForDel=[];params.forEach((v,k)=>{if(v=='')
keysForDel.push(k)});keysForDel.forEach(k=>{params.delete(k)});var utm_params_calendly=params.toString();if(utm_params_calendly){calendly_session_url+='?'+utm_params_calendly}
Calendly.initPopupWidget({url:calendly_session_url,prefill:{name:''+registerFormName,email:''+registerFormEmail,customAnswers:{a0:''+registerFormPhone,}},})}
if(form_id==1&&newsAndOffers){_etmc.push(["setOrgId","510001196"]);_etmc.push(["setUserInfo",{"email":getInTouchEmail}]);_etmc.push(["trackPageView"])}
if(form_id==1){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:"Su_Lead_Submission"})}});$('#gform_1').submit(function(){setTimeout(function(){$('.gform_ajax_spinner').show()},600)});$('#gform_12').submit(function(e){setTimeout(function(){$('.booking-overlay').show()},600)});if($('body.no-cta').length){$('#footer-widget .widget_nav_menu #menu-item-803').remove();$('.no-cta .footer-contact').remove()}
window.registerFormName;window.registerFormEmail;window.registerFormPhone;$('#gform_1').submit(function(){if($('#choice_1_9_1').is(':checked')){}else{}
registerFormName=$('#input_1_1').val();registerFormEmail=$('#input_1_2').val();registerFormPhone=$('#input_1_12').val();setTimeout(function(){$('.gform_ajax_spinner').show()},600)});jQuery(document).on('gform_confirmation_loaded',function(event,formId){if(formId==16){$(".booking-overlay").hide()}
if(formId==1){var SF_Lead_ProductID=getCookie('SF_Lead_ProductID');var SF_Lead_TransactionID=getCookie('SF_Lead_TransactionID');window.dataLayer=window.dataLayer||[];window.dataLayer.push({'ProductID':SF_Lead_ProductID,'TransactionID':'RI'+SF_Lead_TransactionID});eraseCookie('SF_Lead_ProductID');eraseCookie('SF_Lead_TransactionID');var objPush={'finished_flow':!0,'form_name':formName,'source':SF_Lead_ProductID,'ref':SF_Lead_TransactionID};if(typeof brochureTriggeredLead!='undefined'&&brochureTriggeredLead==!0){objPush.brochure_trigger=!0}
amplitude.getInstance().logEvent('submit_lead',objPush)}
if(formId==8){var SF_ContactUs_TransactionID=getCookie('SF_ContactUs_TransactionID');var SF_ContactUs_Category=getCookie('SF_ContactUs_Category');if(!SF_ContactUs_TransactionID){var objPush={'finished_flow':!0,'form_name':'Contact Us','source':'Contact Us'};if(SF_ContactUs_Category){objPush.category=SF_ContactUs_Category}
amplitude.getInstance().logEvent('submit_lead',objPush);return!1}
var objPush={'finished_flow':!0,'form_name':'Contact Us','source':'Contact Us','ref':SF_ContactUs_TransactionID};if(SF_ContactUs_Category){objPush.category=SF_ContactUs_Category}
amplitude.getInstance().logEvent('submit_lead',objPush);eraseCookie('SF_ContactUs_TransactionID');eraseCookie('SF_ContactUs_Category')}});$(window).scroll(function(){if(window.innerWidth<992){var maxScrollPos=0;if($('.cookie-disclaimer').is(":visible")){var cookieHgt=$('.cookie-disclaimer').height();maxScrollPos=74+cookieHgt}else{maxScrollPos=74}
var scrollPos=$(this).scrollTop();if(scrollPos>maxScrollPos){$('.sticky-prop-bar').show();$('#btn-show-filters').addClass('show-hero-video-filter')}else{$('.sticky-prop-bar').hide();$('#btn-show-filters').removeClass('show-hero-video-filter')}}});$(document).ready(function(){function updateQueryStringParameter(uri,key,value){var re=new RegExp("([?&])"+key+"=.*?(&|$)","i");var separator=uri.indexOf('?')!==-1?"&":"?";if(uri.match(re)){return uri.replace(re,'$1'+key+"="+value+'$2')}else{return uri+separator+key+"="+value}}
window.selectedCat='all';window.selectedDate='';$('#searchEvent').on('shown.bs.select',function(e,clickedIndex,isSelected,previousValue){$('body').addClass('datepicker-show');$('.date-overlay').show()});$('#searchEvent').on('hidden.bs.select',function(e,clickedIndex,isSelected,previousValue){$('body').removeClass('datepicker-show');$('.date-overlay').hide()});$('#searchEvent').on('change',function(e){$('body').addClass('datepicker-show');$('.date-overlay').show();var eventType=selectedCat=$(this).val();var url=window.location.href
var arr=url.split("/");if(eventType=='all'){window.location=arr[0]+"//"+arr[2]+'/'+arr[3]+'/'+arr[4]+'/';return}
var redirectURL=arr[0]+"//"+arr[2]+'/'+arr[3]+'/'+arr[4]+window.location.search;window.location=updateQueryStringParameter(redirectURL,'category',eventType);return;var filteredResults=[];$.each(objEvents,function(key,value){if('all'==eventType){if(selectedDate==''){filteredResults.push(value)}else if(value.DATE_FORMAT==selectedDate){filteredResults.push(value)}}else{if(value.CATEGORY.SLUG==eventType&&selectedDate==''){filteredResults.push(value)}else if(value.CATEGORY.SLUG==eventType&&value.DATE_FORMAT==selectedDate){filteredResults.push(value)}}});if(filteredResults.length>0){$('#eventsBlks').empty();var showHtml=renderHTML(filteredResults);$('#eventsBlks').html(showHtml)}else{$('#eventsBlks').html('<div class="col-12 col-sm-12 no-results-found-container"><h3>No Event Available</h3></div>')}});function renderHTML(filteredResults){var html='';for(index=0;index<filteredResults.length;++index){var filteredResult=filteredResults[index];var fDate=filteredResult.DATE;var splitDate=fDate.split(" ");html+='<div class="col-12 col-sm-6 col-md-6 col-lg-4 event-blk">'+'<div class="event-img">'+'<a href="'+filteredResult.LINK+'"><img class="img-fluid" src="'+filteredResult.IMAGE.URL+'" alt="'+filteredResult.IMAGE.ALT+'" title="'+filteredResult.IMAGE.TITLE+'" class="w-100" width="'+filteredResult.IMAGE.WIDTH+'" height="'+filteredResult.IMAGE.HEIGHT+'" ></a>'+'</div>'+'<div class="event-details">'+'<div class="lft-blk">'+'<div class="event-name p-0">'+'<h5>'+filteredResult.LOCATION+'</h5>'+'<a href="'+filteredResult.LINK+'"><h4>'+filteredResult.SLUG+'</h4></a>'+'</div>'+'<div class="event-desc">'+'<p>'+filteredResult.SHORT_CONTENT+'</p>'+'</div>'+'<div class="event-location">'+'<span class="text-capitalize"><i class="far fa-map-marked"></i>'+filteredResult.PLACE+'</span>'+'</div>'+'</div>'+'<div class="rht-blk">'+'<div class="event-cat">'+'<span>'+filteredResult.CATEGORY.NAME+'</span>'+'</div>'+'<div class="event-date">'+'<span>'+splitDate[0]+'</span>'+'<span>'+splitDate[1]+'</span>'+'</div>'+'</div>'+'</div>'+'</div>'}
return html}
function dateObjFilter(date){selectedDate=date;var filteredResults=[];$.each(objEvents,function(key,value){if(value.DATE_FORMAT==date&&selectedCat=='all'){filteredResults.push(value)}else if(value.DATE_FORMAT==date&&selectedCat==value.CATEGORY.SLUG){filteredResults.push(value)}});if(filteredResults.length>0){$('#eventsBlks').empty();var showHtml=renderHTML(filteredResults);$('#eventsBlks').html(showHtml)}else{$('#eventsBlks').html('<div class="col-12 col-sm-12 no-results-found-container"><h3>No Event Available</h3></div>')}}
if($("#calendarBtn").length){setTimeout(function(){$("#calendarBtn").datepicker({showOn:"button",buttonText:"Select date",dayNamesMin:['S','M','T','W','T','F','S'],minDate:0,onClose:function(){$('body').removeClass('datepicker-show');$('.date-overlay').hide()},beforeShow:function(textbox,instance){$('.events-filter-block').append($('#ui-datepicker-div'));$('body').addClass('datepicker-show');$('.date-overlay').show();$('.event-cat-select').selectpicker('destroy');$('.event-cat-select').selectpicker();$('#searchEvent').on('shown.bs.select',function(e,clickedIndex,isSelected,previousValue){$('body').addClass('datepicker-show');$('.date-overlay').show()});$('#searchEvent').on('hidden.bs.select',function(e,clickedIndex,isSelected,previousValue){$('body').removeClass('datepicker-show');$('.date-overlay').hide()})},onSelect:function(dateText,inst){$("input[name='eventDate']").val(dateText);var url=window.location.href
var arr=url.split("/");var redirectURL=arr[0]+"//"+arr[2]+'/'+arr[3]+'/'+arr[4]+window.location.search;window.location=updateQueryStringParameter(redirectURL,'date',dateText);return;dateObjFilter(dateText)}})},300)}
$('.investor-menu-dropdown').on('show.bs.dropdown',function(e){if(window.innerWidth<767){$('body').css('overflow','hidden')}})
$('.investor-menu-dropdown').on('hide.bs.dropdown',function(e){if(window.innerWidth<767){$('body').css('overflow','unset')}});$(window).scroll(function(){var scrollPos=$(this).scrollTop();if(window.innerWidth<=575&&scrollPos>150){$('.investor-enquries-cta').show()}else{$('.investor-enquries-cta').hide()}})});$(window).on('load',function(){if($('#eventsBlks div.no-results-found-container').length){$('div.prop-sort-cont div.row').hide()}
gform.addFilter('gform_datepicker_options_pre_init',function(optionsObj,formId,fieldId){if(formId==6||formId==14||formId==17){if(fieldId==21||fieldId==23||fieldId==25||fieldId==66){optionsObj.minDate=0}}
return optionsObj});gform.addFilter('gform_datepicker_options_pre_init',function(optionsObj,formId,fieldId){if(formId==6){if(fieldId==20){optionsObj.maxDate=0}}
return optionsObj});$('.home .container-search-property input[type="submit"]').on('click',function(){$(".booking-overlay").show()});var url=window.location.href;if(url.includes('#getintouch')){if($('#input_1_6  > option').length==0){$('#input_1_6').html(gform_country_dom);var checkNumber=!1;$('#gform_1 #field_1_6.phone-intl-code select').find('option').each(function(){if(!checkNumber){var val=$(this).text();var hasNumber=/\d/;var checkNumber=hasNumber.test(val)}
if(checkNumber)
return;$(this).append(" "+$(this).val())});$('#gform_1 #gfield_description_1_6 .phone-mask').html($('#gform_1 #field_1_6.phone-intl-code select').val())}
$('#registerModal').modal('show')}});const cookieName='cookieconsent';const cookieValue='dismissed';function dismiss(){const date=new Date();date.setTime(date.getTime()+(10*365*24*60*60*1000));document.cookie=`${cookieName}=${cookieValue};expires=${date.toUTCString()};path=/`;document.querySelector('.disclaimer-content').remove()}
const buttonElement=document.querySelector('.btn-accept');if(buttonElement){buttonElement.addEventListener('click',dismiss)}
if(device!='mobile'){jQuery.event.special.touchstart={setup:function(_,ns,handle){this.addEventListener("touchstart",handle,{passive:!ns.includes("noPreventDefault")})}};jQuery.event.special.touchmove={setup:function(_,ns,handle){this.addEventListener("touchmove",handle,{passive:!ns.includes("noPreventDefault")})}};jQuery.event.special.wheel={setup:function(_,ns,handle){this.addEventListener("wheel",handle,{passive:!0})}};jQuery.event.special.mousewheel={setup:function(_,ns,handle){this.addEventListener("mousewheel",handle,{passive:!0})}}}
$('body').on('hidden.bs.modal','.modal',function(){$('.btn').blur()});var propSearchFloorSelect=document.querySelector('#prop_search_form .floor-options .min-select');propSearchFloorSelect?.addEventListener("change",function(event){document.querySelector('#map_popup_search_form .floor-options .min-select').value=event.target.value})
var propSearchMapfloorSelect=document.querySelector('#map_popup_search_form .floor-options .min-select');propSearchMapfloorSelect?.addEventListener("change",function(event){document.querySelector('#prop_search_form .floor-options .min-select').value=event.target.value})
var propTypeCheckboxes=document.querySelectorAll('#prop_search_form .property-type-selection input[name="p-type[]"]');for(let i=0;i<propTypeCheckboxes.length;i++){propTypeCheckboxes[i]?.addEventListener("change",function(event){event.target.checked?$('#map_search_form #propertyTyp .propChoice input[value="'+event.target.value+'"]').parent().addClass('active'):$('#map_search_form #propertyTyp .propChoice input[value="'+event.target.value+'"]').parent().removeClass('active');$('#map_search_form #propertyTyp .propChoice input[value="'+event.target.value+'"]').attr('checked',event.target.checked);if($('#map_search_form #propertyTyp .propChoice.active').length<1){$('#map_search_form #propertyTyp').siblings('a.filtrBtn').removeClass('active')}else{$('#map_search_form #propertyTyp').siblings('a.filtrBtn').addClass('active')}})}
var propTypeCheckboxes=document.querySelectorAll('#prop_search_form .bedroom-selection input[name="bed[]"]');for(let i=0;i<propTypeCheckboxes.length;i++){propTypeCheckboxes[i]?.addEventListener("change",function(event){event.target.checked?$('#map_search_form #propertyBeds .propChoice input[value="'+event.target.value+'"]').parent().addClass('active'):$('#map_search_form #propertyBeds .propChoice input[value="'+event.target.value+'"]').parent().removeClass('active');$('#map_search_form #propertyBeds .propChoice input[value="'+event.target.value+'"]').attr('checked',event.target.checked);if($('#map_search_form #propertyBeds .propChoice.active').length<1){$('#map_search_form #propertyBeds').siblings('a.filtrBtn').removeClass('active')}else{$('#map_search_form #propertyBeds').siblings('a.filtrBtn').addClass('active')}})}
$(window).on('load',function(){min_price_selection=parseInt($('select[name="min-price"]').children("option:selected").val());max_price_selection=parseInt($('select[name="max-price"]').children("option:selected").val());var minAreaSelect=parseInt($('select[name="min-area"]').children("option:selected").val());var maxAreaSelect=parseInt($('select[name="max-area"]').children("option:selected").val());if(min_price_selection>0){$('select[name="min-price"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem>max_price_selection||currentItem==max_price_selection){$(this).hideOption()}})}
if(max_price_selection<100000000){$('select[name="max-price"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem<max_price_selection){$(this).hideOption()}})}
if(minAreaSelect>0){$('select[name="min-area"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem>maxAreaSelect||currentItem==maxAreaSelect){$(this).hideOption()}})}
if(maxAreaSelect<50000){$('select[name="max-area"] option').each(function(){$(this).showOption();currentItem=parseInt($(this).val());if(currentItem<maxAreaSelect){$(this).hideOption()}})}
$('.clear-selection').each(function(){if($(this).hasClass('active-clear')||$(this).hasClass('active-clearall')){$(this).css('pointer-events','unset')}else{$(this).css('pointer-events','none')}});$('.filter-btn[type="reset"]').each(function(){if($(this).closest('.filter-btns').siblings('.filter-choices').find('.propChoice.active').length>0){$(this).css('pointer-events','unset');$(this).addClass('active-clear')}else{$(this).removeClass('active-clear')
$(this).css('pointer-events','none')}})});document.addEventListener("DOMContentLoaded",function(){var lazyloadImages;if("IntersectionObserver" in window){lazyloadImages=document.querySelectorAll(".lazyload");var imageObserver=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.isIntersecting){var image=entry.target;image.src=image.dataset.src;image.onload=function(){image.classList.remove("lazyload");imageObserver.unobserve(image)}}})});lazyloadImages.forEach(function(image){imageObserver.observe(image)})}else{var lazyloadThrottleTimeout;lazyloadImages=document.querySelectorAll(".lazyload");function lazyloading(){if(lazyloadThrottleTimeout){clearTimeout(lazyloadThrottleTimeout)}
lazyloadThrottleTimeout=setTimeout(function(){var scrollTop=window.pageYOffset;lazyloadImages.forEach(function(img){if(img.offsetTop<(window.innerHeight+scrollTop)){img.src=img.dataset.src;img.classList.remove('lazyload')}});if(lazyloadImages.length==0){document.removeEventListener("scroll",lazyloading);window.removeEventListener("resize",lazyloading);window.removeEventListener("orientationChange",lazyloading)}},20)}
document.addEventListener("scroll",lazyloading);window.addEventListener("resize",lazyloading);window.addEventListener("orientationChange",lazyloading)}});$(document).click(function(e){var modalRyi=$('#registerModal').hasClass('show');if(modalRyi){$("iframe[src*='https://www.google.com/recaptcha/api2/bframe']").each(function(){var captchaBgVisibility=$(this).parent().parent().css('visibility')=='visible';var BgOpacity=$(this).parent().parent().css('opacity')=='1';if(modalRyi&&captchaBgVisibility&&BgOpacity){$('.gform_ajax_spinner').hide();if($('.booking-overlay').is(':visible')){$('.booking-overlay').hide()}}})}});document.addEventListener("DOMContentLoaded",function(){$('.investor-header .investor-menu-dropdown').on('shown.bs.dropdown',function(){if(window.innerWidth>760){$('.investor-header .investor-menu-dropdown .dropdown-menu.show').css('top',$('.investor-header').height()-1)}})});$(".ir-nav-pills .dropdown-menu > .nav-link").on("click",function(){$(this).closest(".dropdown-menu").prev().text($(this).text())})